# 异常Exception
软件程序在运行过程中，遇到文件格式、数据库异常、数据为空、无法打开等等问题不能满足程序继续运行，我们称之为异常，英文是：Exception，意思是例外

Exception是程序本身能够处理的异常，如：空指针异第（NullPointerException）、数组下标越界
异常（ArraylndexOutOfBoundsException）、类型转换异常（ClassCastException）、算术异常（ArithmeticException）等。

Exception类是所有异常类的父类，其子类对应了各种各样可能出现的异常事件。通常Java的异常可分为：
1. RuntimeException 运行时异常
2. CheckedException 已检查异常

如果完全用if语句去控制各种情况
<img src="./pictures/Annotation 2019-10-31 221844.png"  div align=center />

这种方式，有两个坏处：
1. 逻辑代码和错误处理代码放一起！
2. 程序员本身需要考虑的例外情况较复杂，对程序员本身要求较高！
那么，我们如何解决应对异常情况呢？Java的异常机制给我们提供了方便的处理方式。如上情况，如果是用Java的异常机制来处理，示意代码如下（仅限示意，不能运行）：
<img src="./pictures/Annotation 2019-10-31 222022.png"  div align=center />

**异常机制本质**
就是当程序出现错误，程序安全退出的机制。

Java是采用面向对象的方式来处理异常的。处理过程：
**1.抛出异常：** 在执行一个方法时，如果发生异常，则这个方法生成代表该异常的一个对象，停止当前执行路径，并把异常对象提交给JRE。
**2.捕获异常：** JRE得到该异常后，寻找相应的代码来处理该异常。JRE在方法的调用栈中查找，从生成异常的方法开始回溯，直到找到相应的异常处理代码为止。



## 错误ERROR
Error是程序无法处理的错误，表示运行应用程序中较严重问题。大多数错误与代码编写者执行的操作无关，而表示代码运行时JVM（Java虚拟机）出现的问题。例如，Java虚拟机运行错误（Virtual MachineError），当JVM不再有继续执行操作所需的内存资源时，将出现OutOfMemoryError。这些异常发生时，Java虚拟机JVM）一般会选择线程终止。
Error表明系统JVM已经处于不可恢复的崩溃状态中。我们不需要管它
<img src="./pictures/Annotation 2019-10-31 222513.png"  div align=center />


### 运行时异常RuntimeException

派生于RuntimeException的异常，如被0除、数组下标越界、空指针等，其产生比较频繁，处理麻烦，如果显式的声明或捕获将会对程序可读性和运行效率影响很大。因此由系统自动检测并将它们交给缺省的异常处理程序（用户可不必对其处理）。
这类异常通常是由编程错误导致的，所以在编写程序时，并不要求必须使用异常处理机制来处理这类异常，经常需要通过增加“逻辑处理来避免这些异常”。

1. 整数除0
```java
/*试图除以0*/
public static void main(String[] args) {
        int a = 0;
        System.out.println(1/a);
    }
```
异常截图：
<img src="./pictures/Annotation 2019-11-01 093600.png"  div align=center />

只需增加条件判断即可处理
```java
/*试图除以0*/
public static void main(String[] args) {
        int a = 0;
        if(a!=0)
            System.out.println(1/a);
    }
```
当程序访问一个空对象的成员变量或方法，或者访问一个空数组的成员时会发生**空指针异常**（NullPointerException）。

2. 空指针异常
```java
public static void main(String[] args) {
        String str = null;
        str.length();
}
```
<img src="./pictures/Annotation 2019-11-01 094607.png"  div align=center />

增加非空判断 `if(str!=null) ` 即可

在引用数据类型转换时，有可能发生**类型转换异常**（ClassCastException）。

 3. 类型转换异常

```java
class Animals{
}
class Dog extends Animals{
}
class Cat extends  Animals{
}
public static void main(String[] args) {
        Animals a = new Dog();
        Cat c = (Cat) a;
    }
```
<img src="./pictures/Annotation 2019-11-01 095107.png"  div align=center />
也是通过判断来避免这种异常

```java
public static void main(String[] args) {
        Animals a = new Dog();
        if (a instanceof Cat)
            Cat c = (Cat) a;
    }
```

4. 当程序访问一个数组的某个元素时，如果这个元素的索引超出了0~数组长度-1这个范围，则会出现**数组下标越界异常**（ArrayIndexOutOfBoundsException）。

5. 在使用包装类将字符串转换成基本数据类型时，如果字符串的格式不正确，则会出现**数字格式异常**（NumberFormatException）。


### 已检查异常Checked Exception
所有不是RuntimeException的异常，统称为Checked Exception，又被称为“已检查异常”，如IOException、SQLException等以及用户自定义的Exception异常。这类异常在编译时就必须做出处理，否则无法通过编译。如图所示。
<img src="./pictures/Annotation 2019-11-01 095858.png"  div align=center />

### 自定义异常
1. 在程序中，可能会遇到JDK提供的任何标准异常类都无法充分描述清楚我们想要表达的问题，这种情况下可以创建自己的异常类，即自定义异常类。
2. 自定义异常类只需从Exception类或者它的子类派生一个子类即可。
3. 自定义异常类如果继承Exception类，则为受检查异常，必须对其进行处理；如果不想处理，可以让自定义异常类继承运行时异常RuntimeException类。
4. 习惯上，自定义异常类应该包含2个构造器：一个是默认的构造器，另一个是带有详细信息的构造器。

### 异常处理
#### 捕获异常
捕获异常是通过3个关键词来实现的：try-catch-finally。用try来执行一段程序，如果出现异常，系统抛出一个异常，可以通过它的类型来捕捉（catch）并处理它，最后一步是通过finally语句为异常处理提供一个统一的出口，finally所指定的代码都要被执行（catch语句可有多条；finally语句最多只能有一条，根据自己的需要可有可无）。如图所示。
<img src="./pictures/Annotation 2019-11-01 100046.png"  div align=center />

1. **try：**
    try语句指定了一段代码，该段代码就是异常捕获并处理的范围。在执行过程中，当任意一条语句产生异常时，就会跳过该条语句中后面的代码。代码中可能会产生并抛出一种或几种类型的异常对象，它后面的catch语句要分别对这些异常做相应的处理。
一个try语句必须带有至少一个catch语句块或一个finally语句块。
**注意**，当异常处理的代码执行结束以后，**不会回到try语句**去执行尚未执行的代码。

2. **catch：**
n-每个try语句块可以伴随一个或多个catch语句，用于处理可能产生的不同类型的异常对象。
n-常用方法，这些方法均继承自Throwable类。
.toString()方法，显示异常的类名和产生异常的原因
.getMessage()方法，只显示产生异常的原因，但不显示类名。
.printStackTrace()方法，用来跟踪异常事件发生时堆栈的内容。(通常用)
n-catch捕获异常时的捕获顺序：u-如果异常类之间有继承关系，在顺序安排上需注意。越是顶层的类，越放在下面，再不然就接把多余的catch省略掉。也就是**先捕获子类异常再捕获父类异常**。（catch写语句子类在前父类在后，免得子类的异常被父类捕获处理）

3. **finally：**
n-有些语句，不管是否发生了异常，都必须要执行，那么就可以把这样的语句放到finally语句块n-通常在finally中关闭程序块已打开的资源，比如：关闭文件流、释放数据库连接等。

try-catch-finally语句块的执行过程：
try-catch-finally程序块的执行流程以及执行结果比较复杂。

程序首先执行可能发生异常的try语句块。如果try语句没有出现异常则执行完后跳至finally语句块执行；如果try语句出现异常，则中断执行并根据发生的异常类型跳至相应的catch语句块执行处理。
catch语句块可以有多个，分别捕获不同类型的异常。catch语句块执行完后程序会继续执行finally语句块。finally语句是可选的，如果有的话，则不管是否发生异常，finally语句都会被执行。

**注意事项**
1.即使try和catch块中**存在return语句**，**finally语句也会执行**。是在执行完finally语句后再通过return退出。
2.finally语句块只有一种情况是不会执行的，那就是在执行finally之前遇到了System.exit(0)结束程序运行。

#### 声明异常(throws子句)
当CheckedException产生时，不一定立刻处理它，可以再把异常throws出去。
在方法中使用try-catch-finally是由这个方法来处理异常。但是在一些情况下，当前方法并不需要处理发生的异常，而是向上传递给调用它的方法处理。
如果一个方法中可能产生某种异常，但是并不能确定如何处理这种异常，则应根据异常规范在方法的首部声明该方法可能抛出的异常。（调用者处理这个异常）
如果一个方法抛出多个已检查异常，就必须在方法的首部列出所有的异常，之间以逗号隔开。

使用异常机制的建议
1. 要避免使用异常处理代替错误处理|这样会降低程序的清晰性，并且效率低下。
2. 处理异常不可以代替简单测试--只在异常情况下使用异常机制。
3. 不要进行小粒度的异常处理---应该将整个任务包装在一个try语句块中。
今
4. 异常往往在高层处理。